### ISSUE TITLE
only support two language?

### ISSUE THREAD

**Issue by SkullFang** [TencentGameMate/gnn_cross_lingual#3]
May I ask the author, if src_lang and tgt_lang are specified in each training, does this mean that this model only supports two languages? Is it possible to achieve multi-regional language classification?

**Comment by Billijk** [comment]
Hi @SkullFang ,

Thanks for your interest in our work! We set src_lang and tgt_lang for each experiment because we follow previous work on a cross-lingual settings. The model itself can handle more languages together. However, in order to do that, you need to check cross_lingual.py and change the codes related to src_text and tgt_text. Please let me know if you find anything confusing.

**Comment by Billijk** [comment]
I am closing this issue since it's not active. Please reopen it if there's still any question :)

**Comment by Clarioooo** [comment]
Hi author,
I have a trouble when I try to run the code. The src_lang and tgt_lang's train/test/eval.txt cannot be found in slu. If the src_lang==en while the tar_lang==es,  is this right?
<img width="551" alt="image" src="https://github.com/TencentGameMate/gnn_cross_lingual/assets/83835647/4dfabbef-f98f-4abd-b038-0a7fd5f34b3a">
<img width="545" alt="image" src="https://github.com/TencentGameMate/gnn_cross_lingual/assets/83835647/7157eaac-7cfb-4d26-a794-8a9c45b6cb16">
I don't find a txt named eval_en-es.txt or test_en-es. So in the two function, I use the same file.
